# generate_2d_data.jl — Generate 2D field data for publication figures
#
# Produces CSV files for:
#   A. Ez field snapshots at 4 representative times (large domain)
#   B. 2D material map (large domain)
#   C. B-scan receiver positions (for heatmap axis)
#   D. 2D gradient sensitivity map (small domain)
#   (Reconstruction maps are generated by run_fwi_large_domain.jl)

using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))
Pkg.instantiate()

using GPRADFWI
using DelimitedFiles
using Printf
using Random
using LinearAlgebra
using Statistics

datadir = joinpath(@__DIR__, "..", "..", "paper", "data")
mkpath(datadir)

# ══════════════════════════════════════════════════════════════════════════
# PART A & B: Large domain (400×300) — field snapshots + material map
# ══════════════════════════════════════════════════════════════════════════
println("=" ^ 60)
println("Part A & B: Field Snapshots + Material Map (large domain)")
println("=" ^ 60)

Random.seed!(42)

# Domain setup — identical to validate_forward.jl
const domain_x = 2.0    # [m]
const domain_y = 1.5    # [m]
const grid_dx  = 0.005  # [m] (5 mm)
const fc_gpr   = 500e6  # [Hz]

const nx = round(Int, domain_x / grid_dx)   # 400
const ny = round(Int, domain_y / grid_dx)   # 300
const npml = 15

const rx_y = npml + 10
const rx_x_list = collect((npml+5):4:(nx-npml-5))
const src_x = nx ÷ 2
const src_y = rx_y

config = create_config(
    nx=nx, ny=ny, dx=grid_dx, fc=fc_gpr, npml=npml,
    src_ix=src_x, src_iy=src_y,
    rx_iy=rx_y, rx_ix_list=rx_x_list,
)

# Build material model — identical to validate_forward.jl
eps_inf_map = ones(nx, ny)
deps_map    = zeros(nx, ny)
tau_map     = zeros(nx, ny)
sigma_map   = zeros(nx, ny)

surface_j = npml + 20
layer1_top = surface_j
layer1_bot = surface_j + round(Int, 0.6 / grid_dx)

for j in layer1_top:min(layer1_bot, ny), i in 1:nx
    eps_inf_map[i, j] = 4.0
    deps_map[i, j]    = 4.0
    tau_map[i, j]     = 0.3e-9
    sigma_map[i, j]   = 0.005
end

layer2_top = layer1_bot + 1
for j in layer2_top:ny, i in 1:nx
    eps_inf_map[i, j] = 6.0
    deps_map[i, j]    = 12.0
    tau_map[i, j]     = 1.0e-9
    sigma_map[i, j]   = 0.02
end

pipe_cx = round(Int, 1.0 / grid_dx)
pipe_cy = surface_j + round(Int, 0.5 / grid_dx)
pipe_r  = round(Int, 0.05 / grid_dx)

for j in 1:ny, i in 1:nx
    if (i - pipe_cx)^2 + (j - pipe_cy)^2 <= pipe_r^2
        eps_inf_map[i, j] = 15.0
        deps_map[i, j]    = 10.0
        tau_map[i, j]     = 0.5e-9
        sigma_map[i, j]   = 0.001
    end
end

# Snapshot times: ~2ns, ~5ns, ~8ns, ~12ns
snap_times_ns = [2.0, 5.0, 8.0, 12.0]
snap_steps = [round(Int, t * 1e-9 / config.dt) for t in snap_times_ns]
# Clamp to valid range
snap_steps = clamp.(snap_steps, 1, config.nt)

println("Grid: $(nx) × $(ny), dt = $(@sprintf("%.4e", config.dt)) s, nt = $(config.nt)")
println("Snapshot steps: $snap_steps")
println("Snapshot times: $([round(s * config.dt * 1e9, digits=2) for s in snap_steps]) ns")

# Run forward with snapshots
src_waveform = create_source(config)
println("\nRunning forward simulation with snapshots...")
t_start = time()
rec_data, snapshots = run_forward_snapshots(config, eps_inf_map, deps_map, tau_map, sigma_map,
                                             src_waveform, snap_steps)
t_elapsed = time() - t_start
@printf("Done in %.2f s\n", t_elapsed)

# Crop CPML and downsample
i_start = npml + 1
i_end   = nx - npml
j_start = npml + 1
j_end   = ny - npml
ds = 4  # downsample factor

i_range = i_start:ds:i_end
j_range = j_start:ds:j_end
x_phys = [(i - 1) * grid_dx for i in i_range]  # physical x [m]
y_phys = [(j - surface_j) * grid_dx for j in j_range]  # depth from surface [m]

println("Cropped interior: i=$(i_start):$(i_end), j=$(j_start):$(j_end)")
println("Downsampled: $(length(i_range)) × $(length(j_range)) points")

# Save field snapshots
for (k, snap_step) in enumerate(snap_steps)
    t_ns = snap_step * config.dt * 1e9
    fname = @sprintf("field_snapshot_t%02dns.csv", round(Int, snap_times_ns[k]))
    fpath = joinpath(datadir, fname)
    open(fpath, "w") do io
        @printf(io, "# Ez field snapshot at t=%.2f ns (step %d), domain %dx%d, dx=%.0fmm, downsampled %dx, seed=42\n",
                t_ns, snap_step, nx, ny, grid_dx*1e3, ds)
        write(io, "x_m,depth_m,ez_vm\n")
        Ez_snap = snapshots[k]
        for (jj, j) in enumerate(j_range)
            for (ii, i) in enumerate(i_range)
                @printf(io, "%.6e,%.6e,%.6e\n", x_phys[ii], y_phys[jj], Ez_snap[i, j])
            end
        end
    end
    println("  Saved: $fname")
end

# Save 2D material map
mat2d_file = joinpath(datadir, "material_map_2d.csv")
open(mat2d_file, "w") do io
    @printf(io, "# 2D eps_inf map, domain %dx%d, dx=%.0fmm, downsampled %dx\n", nx, ny, grid_dx*1e3, ds)
    write(io, "x_m,depth_m,eps_inf\n")
    for (jj, j) in enumerate(j_range)
        for (ii, i) in enumerate(i_range)
            @printf(io, "%.6e,%.6e,%.6e\n", x_phys[ii], y_phys[jj], eps_inf_map[i, j])
        end
    end
end
println("  Saved: material_map_2d.csv")

# ══════════════════════════════════════════════════════════════════════════
# PART C: B-scan receiver positions
# ══════════════════════════════════════════════════════════════════════════
println("\n" * "=" ^ 60)
println("Part C: B-scan Receiver Positions")
println("=" ^ 60)

bscan_axes_file = joinpath(datadir, "bscan_heatmap_axes.csv")
open(bscan_axes_file, "w") do io
    write(io, "# B-scan receiver x-positions for heatmap plotting\n")
    write(io, "receiver_index,x_position_m\n")
    for (r, ix) in enumerate(rx_x_list)
        x_pos = (ix - 1) * grid_dx
        @printf(io, "%d,%.6e\n", r, x_pos)
    end
end
println("  Saved: bscan_heatmap_axes.csv ($(length(rx_x_list)) receivers)")

# ══════════════════════════════════════════════════════════════════════════
# PART D: Small domain (60×50) — gradient sensitivity map
# ══════════════════════════════════════════════════════════════════════════
println("\n" * "=" ^ 60)
println("Part D: Gradient Sensitivity Map (small domain)")
println("=" ^ 60)

Random.seed!(42)

# Small domain setup — identical to validate_gradients.jl
const nx_small = 60
const ny_small = 50
const dx_small = 0.01  # 1 cm
const fc_small = 300e6
const npml_small = 8

rx_list_small = collect((npml_small+2):3:(nx_small-npml_small-2))
rx_y_small = npml_small + 5
src_x_small = nx_small ÷ 2
src_y_small = rx_y_small

config_small = create_config(
    nx=nx_small, ny=ny_small, dx=dx_small, fc=fc_small, npml=npml_small,
    src_ix=src_x_small, src_iy=src_y_small,
    rx_iy=rx_y_small, rx_ix_list=rx_list_small,
    nt=300,
)

# True model
eps_inf_true = 3.0 * ones(nx_small, ny_small)
deps_true    = zeros(nx_small, ny_small)
tau_true     = zeros(nx_small, ny_small)
sigma_true   = 0.001 * ones(nx_small, ny_small)

anomaly_i = nx_small ÷ 2
anomaly_j = ny_small ÷ 2
anomaly_r = 3
for j in 1:ny_small, i in 1:nx_small
    if (i - anomaly_i)^2 + (j - anomaly_j)^2 <= anomaly_r^2
        eps_inf_true[i, j] = 6.0
    end
end

# Generate observed data
src_wf_small = create_source(config_small)
println("Generating observed data (small domain)...")
obs_data = run_forward!(config_small, eps_inf_true, deps_true, tau_true, sigma_true, src_wf_small)

# Inversion mask: 13×13 region around anomaly
param_mask = falses(nx_small, ny_small)
inv_region = 6
for j in (anomaly_j-inv_region):(anomaly_j+inv_region)
    for i in (anomaly_i-inv_region):(anomaly_i+inv_region)
        if 1 <= i <= nx_small && 1 <= j <= ny_small
            param_mask[i, j] = true
        end
    end
end
n_params = count(param_mask)
println("Inversion parameters: $n_params cells")

# Background model
eps_inf_bg = 3.0 * ones(nx_small, ny_small)
sigma_bg = 0.001 * ones(nx_small, ny_small)

# ── Gradient sensitivity map ────────────────────────────────────────
println("\nComputing AD gradient for sensitivity map...")
function obj_eps(x_flat)
    return forward_misfit(x_flat, config_small, obs_data, src_wf_small,
                          eps_inf_bg, deps_true, tau_true, sigma_bg,
                          param_mask, :eps_inf)
end

x0 = Float64[]
for j in 1:ny_small, i in 1:nx_small
    if param_mask[i, j]
        push!(x0, eps_inf_bg[i, j])
    end
end

grad_ad = ad_gradient(obj_eps, x0)
println("  |grad| = $(@sprintf("%.6e", norm(grad_ad)))")

# Map gradient back to 2D spatial positions
grad_file = joinpath(datadir, "gradient_sensitivity_2d.csv")
open(grad_file, "w") do io
    write(io, "# 2D gradient magnitude map, $(count(param_mask)) params in inversion region, dx=$(dx_small*100)cm, seed=42\n")
    write(io, "x_cm,depth_cm,grad_magnitude\n")
    idx = 1
    for j in 1:ny_small, i in 1:nx_small
        if param_mask[i, j]
            x_cm = (i - 1) * dx_small * 100.0
            depth_cm = (j - rx_y_small) * dx_small * 100.0
            @printf(io, "%.4f,%.4f,%.6e\n", x_cm, depth_cm, abs(grad_ad[idx]))
            idx += 1
        end
    end
end
println("  Saved: gradient_sensitivity_2d.csv")

println("\n=== All 2D data generated ===")
